name: Publish Package

on:
  push:
    branches:
      - main  # Change this to your release branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install 

      - name: Build package
        run: yarn build

      - name: Bump version
        run: yarn version --patch --no-git-tag-version

      - uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          fetch: true
          message: '@chore: bump version'

      - name: Publish package
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
